### ISSUE TITLE
[FEATURE] Integration with Monk's Token Bar

### ISSUE THREAD

**Issue by Kharmans** [FaeyUmbrea/obs-utils#148]
When stream through OBS Utils, every window, app, module and etc became invisible to the stream, except Monk's Token Bar.
Can it be worked with Monk to make it invisible too?

![image](https://github.com/FaeyUmbrea/obs-utils/assets/112586547/ade22ca3-1915-4a8e-ac08-0d471f242338)

Another one that became visible too is the window of YouTube Player Widget, from The Ripper93, but I think that one is not possible to make it invisible, but if it could, would be good!

**Comment by FaeyUmbrea** [comment]
Hi there, sorry for the long wait.
While it would be possible to support monks token bar, it would mean that I would have to maintain the fix for this special case throughout all updates of monk's module, my fix would break everytime something changes about how the token bar is rendered, even small things such as the class name of the bar display changing. As I do not personally use monks token bar, I don't think I can provide adequate support for it. Although contributions that do so would be welcome!

It would be even better if someone who was dedicated to supporting monks token bar, or monk themselves used the provided "obs-utils.init" Hook, or better the new "obs-utils.streamModeInit" that is going to be in the next update. 
The second one is only fired if OBS mode is initialized, and as such can be used to detect when UI should be hidden.

Regarding TheRipper93's module. As it is a paid premium module, I will not be adding support for it, as I do not have the module, and have no intention of buying it.
