### ISSUE TITLE
[FEATURE] Integration with DSN

### ISSUE THREAD

**Issue by itsmegrave** [FaeyUmbrea/obs-utils#149]
Hey!
There's any plans to add Dice so Nice! rolling effect in /stream view?

**Comment by FaeyUmbrea** [comment]
Hello!
Supporting third party modules can make the project more complex. Since I am not personally familiar with Dice so Nice, I would like to gauge the interest of the community before considering adding compatibility for it. 
To gather public opinion quickly, I have created a vote in the feature request section of my Discord. 
For now, I will be closing this issue. However, if there is enough demand from users (or if one of my high-tier Patreon supporters requests this feature through their pledge benefits), I will be happy to add it to the module.
