### ISSUE TITLE
Combat Tab / Initiative tracker does not display

### ISSUE THREAD

**Issue by jalensailin** [FaeyUmbrea/obs-utils#151]
Issue: In `/game` view, the combat tab does not display, even in an active combat. Instead, all you get is the collapsed sidebar (with all icons visible). If you enter with a combat already active, nothing displays. Obviously you can go in and open it yourself, but if you don't remember, then you're SOL

![image](https://github.com/user-attachments/assets/7012cd5a-50ac-4700-ae8e-0ee4a90243f8)

Expected Behavior: Combat tab shows during game view when a combat is active (and no other icons)

I can confirm I am using latest chrome when testing, not using an OBS browser source. 

Foundry Version: v12.303
PF2e: 1.6.2

**Comment by FaeyUmbrea** [comment]
Hello there! I noticed that there is a bug caused by V12, but I wanted to clarify that the expected behavior you mentioned is not quite accurate. Actually, the entire sidebar will be displayed with the combat tracker tab being active. After the combat ends, the sidebar will be hidden again. The reason for this is that the popout tracker is currently unusable for this feature as this is how it looks:
![image](https://github.com/user-attachments/assets/dc459b9b-b42b-421d-8692-19df27d9066c)

**Comment by jalensailin** [comment]
understood. thanks for the fix!
